### ISSUE TITLE
how to use changed api.NewSession internface

### ISSUE THREAD

**Issue by mosasiru** [pogodevorg/pogo#10]
api.NewSession argument changed. *Feed is added.
How to use new interface?

**Comment by zeevallin** [comment]
Right, so you can create a feed together with a reporter. The reporter is an interface you can use to take action on found data, like so:

``` go
type MyReporter struct{}
func (r *MyReporter) WildPokemons([]*protos.WildPokemon) {
    // Do something when you find wild pokemon
}
func (r *MyReporter) Forts([]*protos.FortData) {
    // Do something when you find forts
}

func main() {
  // ...
  feed := api.NewFeed(&MyReporter{})
  session := api.NewSession(provider, location, feed, false)
  session.Init()
}
```

Sorry about breaking the API without documenting. I will make a release tag as soon as this library is minimally viable and stable. :)

**Comment by simonklee** [comment]
What is the rationale behind this API?
Why can't you just create this functionality externally in a client application?

With this design; for every new type you have to remember to update the feed reporter, extend the feed interface (breaking the API).

**Comment by zeevallin** [comment]
@simonz05 You bring up a valid point. I realised the same thing earlier. This is subject to change until I tag a release later this weekend to beginning of next week.

**Comment by mosasiru** [comment]
thank you very much!

**Comment by mosasiru** [comment]
another topic.
niantic API is sometimes very slow (about 30sec),
so I want to add Timeout option to http client, but `Session.rpc` is a private field, so unchangable.

so I suggest that `api.NewSession` can change all fields, and another method `api.SimpleNewSesison` (just idea) supply a little argument.
How about it?
I want to controll timeout.

**Comment by mosasiru** [comment]
another topic.
niantic API is sometimes very slow (about 30sec),
so I want to add Timeout option to http client, but `Session.rpc` is private field, so unchangable.
so I suggest that `api.NewSession` can change all fields, and another method `api.SimpleNewSesison` (just idea) supply a little argument.
How about it ? I want to controll timeout.

**Comment by zeevallin** [comment]
As suggested by @simonz05 the reporter was a bit too strict, leaving any users of the library with having to implement all reporter functions in their own reporter implementations. I've changed this so that feed has become an interface you can implement to create your own reporting. Added examples in the README.
