### ISSUE TITLE
panic: Index out of range in api/session.go

### ISSUE THREAD

**Issue by moddyz** [pogodevorg/pogo#12]
Reproduction:
1. Create new Session
2. Initialize Session
3. Call session.GetPlayerMap()

It seems that protos.ResponseEnvelope.Returns could at times be an empty slice?

Stacktrace:

```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x414ee0, 0xc82000a0b0)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/pkmngo-odi/pogo/api.(*Session).GetPlayerMap(0xc820012550, 0x1, 0x0, 0x0)
    /Users/Moddy/go/src/github.com/pkmngo-odi/pogo/api/session.go:223 +0x47a
main.main()
    /Users/Moddy/go/src/github.com/moddyz/pokemapgo/test.go:49 +0x59b
```

**Comment by zeevallin** [comment]
Hmm, have not been able to reproduce it. But I guess we could safe-guard by checking the length of the byte-slice to not be empty and return an error if it is. Thanks for your feedback.

**Comment by moddyz** [comment]
Thanks for looking at this so quick!
