### ISSUE TITLE
Bad wiretype error when calling Session.GetPlayerMap or Announce

### ISSUE THREAD

**Issue by moddyz** [pogodevorg/pogo#15]
To reproduce, basically set up a valid Session, initialize it, and call GetPlayerMap or Announce.

Error message:

```
The response could not be read: proto: bad wiretype for field protos.GetMapObjectsResponse.MapCells: got wiretype 0, want 2
```

**Comment by nazwa** [comment]
@moddyz did you find a solution to this?

**Comment by zeevallin** [comment]
I think this is an edge case where the response returns a proto message that is empty. We should safe-guard, but I want to make sure exactly what it is.

**Comment by moddyz** [comment]
Still waiting on the devs to figure out unknown6... It looks like they're almost done!

**Comment by nazwa** [comment]
Ah, so the problem is linked with the recent api change? Great, good to know!

**Comment by moddyz** [comment]
Oh no, I just meant I haven't done any work on it since the API change, since map requests return nothing :(

Based on the date of when I saw this issue, I think it's unrelated.  I think the API broke 3 days ago - I saw this on the day before

**Comment by zeevallin** [comment]
@moddyz @nazwa since the encrypt lib is now reverse engineered, I will start working on an implementation for that then get back to dealing with issues.

**Comment by moddyz** [comment]
@zeeraw @nazwa  I've been testing the python API.  Looks like an account needs to accept the T&C now before proper map data is returned.   Just droppin a note

**Comment by nazwa** [comment]
Ha, how sneaky. I'll give that a go in a second!

**Comment by zeevallin** [comment]
Come to the discord channel and ask for access to magiclib™ in the #golang channel.
