### ISSUE TITLE
Error when running "go get ...."

### ISSUE THREAD

**Issue by sb89** [pogodevorg/pogo#19]
I am receiving the following error when attempting to run `go get -u github.com/pokeintel/pogo
`

> Cloning into 'POGOProtos'...
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of 'git@github.com:AeonLucid/POGOProtos.git' into submodule path 'POGOProtos' failed
> package github.com/pokeintel/pogo-protos: exit status 128

This could well be something to do with my setup, but I thought I'd ask here in case anyone else is getting the same thing.

**Comment by zeevallin** [comment]
It should be fixed now.
