### ISSUE TITLE
Update to use new protobuffs?

### ISSUE THREAD

**Issue by sb89** [pogodevorg/pogo#20]
It seems like the protobuffs have changed, I'm getting the following errors:

> ../github.com/pokeintel/pogo/api/session.go:147: cannot use requestHash (type []uint64) as type []int64 in field value
> ../github.com/pokeintel/pogo/api/session.go:148: cannot use locationHash1 (type uint32) as type uint64 in field value
> ../github.com/pokeintel/pogo/api/session.go:149: cannot use locationHash2 (type uint32) as type uint64 in field value
> ../github.com/pokeintel/pogo/api/session.go:150: unknown protos.Signature field 'Unknown22' in struct literal

**Comment by zeevallin** [comment]
Working on update.

**Comment by zeevallin** [comment]
Fixed.
