### ISSUE TITLE
Are Pokemon being returned by the API?

### ISSUE THREAD

**Issue by sb89** [pogodevorg/pogo#24]
I'm doing `session.GetPlayerMap(ctx)` and then iterating over the cells and calling `GetWildPokemons()` but nothing is being returned. Is anyone else having the same problem?

**Comment by zeevallin** [comment]
What location are you trying? Could you share the coordinates so I could test too.

**Comment by sb89** [comment]
Lon: -2.0993328094482426,
Lat: 57.1467056707739

**Comment by sb89** [comment]
```
    ctx := context.Background()

    // Initialize a new authentication provider to retrieve an access token
    provider, err := auth.NewProvider("ptc", "username", "password")
    if err != nil {
        log.Fatal(err)
    }

    // Set the coordinates from where you're connecting
    location := &api.Location{
        Lon: -2.0993328094482426,
        Lat: 57.1467056707739,
        Alt: 1,
    }

    // Set up a feed to where all the responses will be pushed
    // The void feed will do nothing with the response entries
    feed := &api.VoidFeed{}

    // Set up the type of crypto to use for signing requests
    //
    // For most intents and purposes, you should be fine with
    // using the Default crypto.
    crypto := encrypt.NewCrypto()
    session := api.NewSession(provider, location, feed, crypto, false)
    // Start new session and connect
    err = session.Init(ctx)
    if err != nil {
        log.Fatal(err)
    }

    resp, err := session.GetPlayerMap(ctx)
    if err != nil {
        log.Fatal(err)
    }

    for _, cell := range resp.MapCells {
        log.Println(cell.WildPokemons)
        log.Println(cell.NearbyPokemons)
        log.Println(cell.CatchablePokemons)
    }
```

**Comment by sb89** [comment]
I don't think it's the coordinates that are the problem, I've tried different ones but with no success.

**Comment by zeevallin** [comment]
Played around and it definitely has to do with the accuracy not matching in the signature. I'm going to fix it all up.

**Comment by zeevallin** [comment]
So, the first issue is that the accuracy didn't match up. Pushing a fix for that soon.

The other issue is that there's a difference between go `1.6` and `1.7`. While running `1.7` I'm no longer receiving map cells.

**Comment by zeevallin** [comment]
Fixed by updating the hashing library to use the one written in go one since the cgo version stopped working in go `1.7`. https://github.com/pogodevorg/pgoapi-go/commit/28cf05e1b54dfb728487188e165dcb4369159ec3
