### ISSUE TITLE
GetPlayerMap only get cell_id?

### ISSUE THREAD

**Issue by VincentSai** [pogodevorg/pogo#27]
when I call GetPlayerMap() only get this return
{"map_cells":[{"s2_cell_id":6251754337001799680,"current_timestamp_ms":1472965820289},{"s2_cell_id":6251754343444250624,"current_timestamp_ms":1472965820289},{"s2_cell_id":6251754341296766976,"current_timestamp_ms":1472965820289},{"s2_cell_id":6251754332706832384,"current_timestamp_ms":1472965820289},{"s2_cell_id":6251754345591734272,"current_timestamp_ms":1472965820289}],"status":1}
is this right?

**Comment by femot** [comment]
Are you using `DefaultCrypto`?

**Comment by j16sdiz** [comment]
Are there any libencrypt.so crypto somewhere on the internet?

**Comment by VincentSai** [comment]
yes, I'm using DefaultCrypto, same issue on using
pgoapi-go -u <username> -p <Secret1234> --lat 24.148332 --lon 120.664729 map

**Comment by femot** [comment]
You need to use a proper `Crypto` implementation. It's not included because of copyright issues with Niantics `encrypt.c`.
