### ISSUE TITLE
CellIds

### ISSUE THREAD

**Issue by jroosing** [pogodevorg/pogo#9]
Hey,

Don't know how else to come in contact, but what is the idea behind the cell ids? Do you create a grid on the map and then determine the location within the grid? 

Really learning a lot from your code base, trying to find my place in doing actual contributions (just a beginner in golang).

Thanks for the inspiration anyway!

**Comment by zeevallin** [comment]
Hi @joeyroosing,

I'm happy you're learning from the code. Cells are basically a mathematically derived slice of the surface of a sphere to a compact format. [I recommend this article to learn more about how it works.](http://blog.christianperone.com/2015/08/googles-s2-geometry-on-the-sphere-cells-and-hilbert-curve/)

Hope that helps!
